name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version (e.g. 1.2.3)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Validate version format and tag existence
        run: |
          VERSION="${{ github.event.inputs.version }}"

          # Check version format: major.minor.patch (e.g., 1.2.3)
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: '$VERSION'. Use semantic versioning (e.g. 1.2.3)."
            exit 1
          fi

          # Check if the tag already exists
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag 'v$VERSION' already exists. Please use a new version."
            exit 1
          fi

          echo "Version '$VERSION' is valid and not tagged yet."

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Tag release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://engtutor-fe --delete